### ISSUE TITLE
Allow configuration to strictly indent two spaces

### ISSUE THREAD

**Issue by kumarshantanu** [BetterThanTomorrow/calva-fmt#5]
Our team members use different editors, so we have agreed upon "strictly two space indentation" to reduce the whitespace noise in commits/pull requests. This is easily configured in Emacs, Vim and Eclipse/CounterClockWise. I would love this optional feature to be in Calva too.

**Comment by PEZ** [comment]
Hello! Sorry, I have missed this issue totally. But I have also tried to get this configuration in (if I understand it correctly) and so far failed. Mainly because of what might be a bug in `cljfmt`: https://github.com/weavejester/cljfmt/issues/154

If you know how to configure cljfmt to do it, please let me know.

Again, sorry for majorly belated answer!

**Comment by PEZ** [comment]
Archiving this repo now, please open any remaining issues against the [Calva repository](/BetterThanTomorrow/calva).
